# Generated by Django 3.1.2 on 2021-03-26 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_type', models.PositiveIntegerField()),
                ('lane_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RedLane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_stop_name', models.CharField(max_length=200)),
                ('red_lane_price', models.PositiveIntegerField()),
                ('red_extra_price', models.PositiveIntegerField()),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lane')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_add', models.CharField(max_length=200)),
                ('to_add', models.CharField(max_length=200)),
                ('current_date', models.DateField()),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lane')),
            ],
        ),
        migrations.CreateModel(
            name='GreenLane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_stop_name', models.CharField(max_length=200)),
                ('green_lane_price', models.PositiveIntegerField()),
                ('green_extra_price', models.PositiveIntegerField()),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lane')),
            ],
        ),
        migrations.CreateModel(
            name='BlueLane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_green_stop_name', models.CharField(max_length=200)),
                ('blue_lane_price', models.PositiveIntegerField()),
                ('blue_extra_price', models.PositiveIntegerField()),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lane')),
            ],
        ),
    ]
