# Generated by Django 3.1.2 on 2021-03-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='price',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='bluelane',
            name='blue_extra_price',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='bluelane',
            name='blue_lane_price',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='greenlane',
            name='green_extra_price',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='greenlane',
            name='green_lane_price',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='redlane',
            name='red_extra_price',
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name='redlane',
            name='red_lane_price',
            field=models.FloatField(default=True),
        ),
    ]
